# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-02 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='cover',
            field=models.ImageField(default='cover_images/no_img.jpg', upload_to='cover_images'),
        ),
    ]
